### ISSUE TITLE
Was it based on some existing distro?

### ISSUE THREAD

**Issue by sskras** [Aalbus-linux/Aalbus#11]
Or is it completely independent distro?

I have hard time finding the answer.

**Comment by sskras** [comment]
FWIW, my best guess is that it's probably based on NetBSD.

**Comment by anoraktrend** [comment]
It uses a lot of NetBSD userland but this project originally started life as a Gentoo stage4

**Comment by staalmannen** [comment]
Indeed it built from a Gentoo stage 4 that I made, so that was my first musl/clang toolchain. At the moment I am following Chimera (chimera-linux.org) development with interest. A lot of overlapping aims (FreeBSD userland rather than NetBSD like I use, but other than that very similar). This last year I have had very little time to work on Aalbus due to real-life issues. I hope to pick up on it again and then I might learn something from what the Chimera guys are doing.

**Comment by sskras** [comment]
Thank you both for the information.

Chimera Linux uses probably different package manager instead.
It seems that Aalbus Linux is the only distro that uses `pkgsrc` and is still not terminated.

Other were:
[Bluewall GNU/Linux](https://distrowatch.com/table.php?distribution=bluewall),
[VoltaLinux](https://distrowatch.com/table.php?distribution=voltalinux),
[Draco Linux](https://distrowatch.com/table.php?distribution=draco),
[Caprice Linux](https://capricelinux.org/faq/) and
"[kaashif Linux](https://kaashif.co.uk/2014/04/03/creating-a-gnu-linux-distro/)" (I made up the name as it had none before termination).
