### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by aosync** [Aalbus-linux/Aalbus#5]
Interesting work! I need to OS-hop back to Linux from OpenBSD for reasons, and Aalbus seems like a great project to keep the *BSD mood. I might be willing to try and play around with it, but I have a few questions.
- Will pkgsrc remain the package manager ? Do you plan on adopting/creating a specific package manager with custom repositories (that would (or not) be complementary to pkgsrc). What are your thoughts about pkgsrc, do you see it more as temporary solution or is it gonna stay that way ?
- How will you handle pkgsrc packages that do not compile out of the box on musl (if that happens)? I am not very familiar with pkgsrc, but is there some overlay system or something to easily add patches for different platforms?
- Does the project have an irc/discord/matrix channel/server, or some other way for users to communicate ?

**Comment by staalmannen** [comment]
Hi! Great to see some interest :) (btw I am in Ghent)

- I will keep pkgsrc as package manager. End users will use the binary part of the package manager to install packages and developers will use pkgsrc. The big attraction with this solution is that it is cross-platform out of the box and would (theoretically) give thousands of packages to the distribution even when the community is small.
- At the moment I am shamelessly hacking the packages (hence why I included /usr/pkgsrc in my last tarball). There should be "proper" solutions to keep OS-specific patches in a different directory. I still need to learn pkgsrc, but the aim would be to stay as "vanilla" possible and rely on/contribute to upstream pkgsrc. I also think it is pretty proper that I go for pkgsrc since most of the userland is NetBSD-derived. I have however noticed some weird things: nbase "env" seems to fail on several packages, so I have a fallback to sbase "env". I would assume that NetBSD utilities should be made to be working with pkgsrc out of the box...
- If the project had an irc/discord/matrix channel it would have been me talking to myself :) When there is a community this would definitely be interesting. Right now I have mostly been concerned by the technical side, to get a bootable image. I have no idea how to take the next step...

**Comment by staalmannen** [comment]
BTW let me know if you want to join the Aalbus-linux project. With the latest tarball, it should be easy to get started.

**Comment by staalmannen** [comment]
An old project that might be interesting to look at is Snowflake linux, which was musl-based and explored per-package namespaces with pkgsrc. This would also solve the annoying PLIST conflicts that I often get between packages.

https://github.com/GregorR/snowflake

**Comment by staalmannen** [comment]
I just made a reddit community:
https://www.reddit.com/r/aalbuslinux/

I will try to make a discord later and then update the github info to point users to those.

**Comment by staalmannen** [comment]
Made a discord too:

https://discord.gg/8fg4uP3vgY

**Comment by staalmannen** [comment]
I have now updated the README with links to Reddit and Discord. Hopefully will that help.
